import * as Icons from 'components/Icons'

export const menus = [
  {
    id: 'dealership',
    name: 'dealership',
    icon: <Icons.DealershipIcon />,
    iconActive: <Icons.DealershipIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
    isDisable: false,
  },
  {
    id: 'bank',
    name: 'bank',
    icon: <Icons.BankIcon />,
    iconActive: <Icons.BankIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
    isDisable: false,
  },
  {
    id: 'garage',
    name: 'garage',
    icon: <Icons.GarageIcon />,
    iconActive: <Icons.GarageIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
    isDisable: false,
  },
  {
    id: 'speedshop',
    name: 'speedshop',
    icon: <Icons.SpeedshopIcon />,
    iconActive: <Icons.SpeedshopIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
    isDisable: false,
  },
  {
    id: 'marketplace',
    name: 'marketplace',
    icon: <Icons.MarketplaceIcon />,
    iconActive: <Icons.MarketplaceIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
    isDisable: true,
  },
  {
    id: 'trade',
    name: 'trade',
    icon: <Icons.TradeIcon />,
    iconActive: <Icons.TradeIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: true,
    isDisable: true,
  },
  {
    id: 'farms',
    name: 'trade/farms',
    icon: <Icons.FarmsIcon />,
    iconActive: <Icons.FarmsIcon color={`#23D0FF`} />,
    isSubMenu: true,
    hasSubMenu: false,
    isDisable: false,
  },
  {
    id: 'tag forge',
    name: 'trade/tagforge',
    icon: <Icons.FarmsIcon />,
    iconActive: <Icons.FarmsIcon color={`#23D0FF`} />,
    isSubMenu: true,
    hasSubMenu: false,
    isDisable: false,
  },
  {
    id: 'pools',
    name: 'trade/pools',
    icon: <Icons.PoolsIcon />,
    iconActive: <Icons.PoolsIcon color={`#23D0FF`} />,
    isSubMenu: true,
    hasSubMenu: false,
    isDisable: true,
  },
  {
    id: 'migrate',
    name: 'trade/migrate',
    icon: <Icons.SwapIcon />,
    iconActive: <Icons.SwapIcon color={`#23D0FF`} />,
    isSubMenu: true,
    hasSubMenu: false,
    isDisable: false,
  },
  // {
  //   id: 'games',
  //   name: 'games',
  //   icon: <Icons.GamesIcon />,
  //   iconActive: <Icons.GamesIcon color={`#FFAE00`} />,
  //   isSubMenu: false,
  //   hasSubMenu: false,
  //   isDisable: true,
  // },
  {
    id: 'missions',
    name: 'mission',
    icon: <Icons.MissionIcon />,
    iconActive: <Icons.MissionIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
    isDisable: false,
  },
  {
    id: 'bridge',
    name: 'bridge',
    icon: <Icons.BridgeIcon />,
    iconActive: <Icons.BridgeIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
    isDisable: false,
  },
  {
    id: 'shop',
    name: 'shop',
    icon: <Icons.ShopIcon width={18} height={18} />,
    iconActive: <Icons.ShopIcon color={`#FFAE00`} width={18} height={18} />,
    isSubMenu: false,
    hasSubMenu: false,
    isDisable: false,
  },
  {
    id: 'inventory',
    name: 'inventory',
    icon: <Icons.InventoryIcon width={18} height={18} />,
    iconActive: <Icons.InventoryIcon color={`#FFAE00`} width={18} height={18} />,
    isSubMenu: false,
    hasSubMenu: false,
    isDisable: false,
  },
]
